# Generated by Django 3.1.1 on 2021-01-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='error_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyword',
            name='is_forced_stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='is_streaming',
            field=models.BooleanField(default=True),
        ),
    ]
